/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as NetworkLayoutRouteImport } from './app/routes/network/_layout'
import { Route as AuthLayoutRouteImport } from './app/routes/_auth/_layout'
import { Route as AppLayoutRouteImport } from './app/routes/_app/_layout'
import { Route as AppLayoutIndexRouteImport } from './app/routes/_app/_layout/index'
import { Route as AppLayoutNotFoundRouteImport } from './app/routes/_app/_layout/$notFound'
import { Route as NetworkLayoutServerIndexRouteImport } from './app/routes/network/_layout/server/index'
import { Route as NetworkLayoutClientIndexRouteImport } from './app/routes/network/_layout/client/index'
import { Route as AppLayoutSettingsIndexRouteImport } from './app/routes/_app/_layout/settings/index'
import { Route as AppLayoutScheduleIndexRouteImport } from './app/routes/_app/_layout/schedule/index'
import { Route as AppLayoutOrdersIndexRouteImport } from './app/routes/_app/_layout/orders/index'
import { Route as AppLayoutNotificationsIndexRouteImport } from './app/routes/_app/_layout/notifications/index'
import { Route as AppLayoutMeIndexRouteImport } from './app/routes/_app/_layout/me/index'
import { Route as AppLayoutLogoutIndexRouteImport } from './app/routes/_app/_layout/logout/index'
import { Route as AppLayoutEmployeesIndexRouteImport } from './app/routes/_app/_layout/employees/index'
import { Route as AppLayoutCustomersIndexRouteImport } from './app/routes/_app/_layout/customers/index'
import { Route as AppLayoutBookingsIndexRouteImport } from './app/routes/_app/_layout/bookings/index'
import { Route as AppLayoutSettingsSystemIndexRouteImport } from './app/routes/_app/_layout/settings/system/index'
import { Route as AppLayoutMeSecurityIndexRouteImport } from './app/routes/_app/_layout/me/security/index'
import { Route as AppLayoutEmployeesUsersIndexRouteImport } from './app/routes/_app/_layout/employees/users/index'
import { Route as AppLayoutCustomersCreateIndexRouteImport } from './app/routes/_app/_layout/customers/create/index'
import { Route as AppLayoutCustomersCustomer_idIndexRouteImport } from './app/routes/_app/_layout/customers/$customer_id/index'
import { Route as AppLayoutCompanyCreateIndexRouteImport } from './app/routes/_app/_layout/company/create/index'
import { Route as AppLayoutBusinessServicesIndexRouteImport } from './app/routes/_app/_layout/business/services/index'
import { Route as AppLayoutBusinessLocationsIndexRouteImport } from './app/routes/_app/_layout/business/locations/index'
import { Route as AppLayoutBookingsCreateIndexRouteImport } from './app/routes/_app/_layout/bookings/create/index'
import { Route as AppLayoutBookingsBooking_idIndexRouteImport } from './app/routes/_app/_layout/bookings/$booking_id/index'
import { Route as AppLayoutEmployeesScheduleEmployee_idRouteImport } from './app/routes/_app/_layout/employees/schedule/$employee_id'
import { Route as AppLayoutEmployeesUsersCreateIndexRouteImport } from './app/routes/_app/_layout/employees/users/create/index'
import { Route as AppLayoutEmployeesUsersEmployee_idIndexRouteImport } from './app/routes/_app/_layout/employees/users/$employee_id/index'
import { Route as AppLayoutBusinessServicesCreateIndexRouteImport } from './app/routes/_app/_layout/business/services/create/index'
import { Route as AppLayoutBusinessServicesService_idIndexRouteImport } from './app/routes/_app/_layout/business/services/$service_id/index'
import { Route as AppLayoutBusinessLocationsCreateIndexRouteImport } from './app/routes/_app/_layout/business/locations/create/index'
import { Route as AppLayoutBookingsBooking_idResultIndexRouteImport } from './app/routes/_app/_layout/bookings/$booking_id/result/index'
import { Route as AppLayoutBookingsBooking_idEditIndexRouteImport } from './app/routes/_app/_layout/bookings/$booking_id/edit/index'
import { Route as AppLayoutBookingsBooking_idCheckoutIndexRouteImport } from './app/routes/_app/_layout/bookings/$booking_id/checkout/index'
import { Route as AppLayoutEmployeesUsersEmployee_idServicesIndexRouteImport } from './app/routes/_app/_layout/employees/users/$employee_id/services/index'
import { Route as AppLayoutEmployeesUsersEmployee_idPasswordIndexRouteImport } from './app/routes/_app/_layout/employees/users/$employee_id/password/index'
import { Route as AppLayoutEmployeesUsersEmployee_idEditIndexRouteImport } from './app/routes/_app/_layout/employees/users/$employee_id/edit/index'
import { Route as AppLayoutBusinessServicesService_idLocationsIndexRouteImport } from './app/routes/_app/_layout/business/services/$service_id/locations/index'
import { Route as AppLayoutBusinessServicesService_idEmployeesIndexRouteImport } from './app/routes/_app/_layout/business/services/$service_id/employees/index'
import { Route as AppLayoutBusinessServicesService_idEditIndexRouteImport } from './app/routes/_app/_layout/business/services/$service_id/edit/index'
import { Route as AppLayoutBusinessLocationsLocationLocation_idIndexRouteImport } from './app/routes/_app/_layout/business/locations/_location/$location_id/index'
import { Route as AppLayoutBusinessLocationsLocationLocation_idEditIndexRouteImport } from './app/routes/_app/_layout/business/locations/_location/$location_id/edit/index'

const AuthLayoutRegisterLazyRouteImport = createFileRoute(
  '/_auth/_layout/register',
)()
const AuthLayoutLoginLazyRouteImport = createFileRoute('/_auth/_layout/login')()
const AuthLayoutInviteLazyRouteImport = createFileRoute(
  '/_auth/_layout/invite',
)()

const NetworkLayoutRoute = NetworkLayoutRouteImport.update({
  id: '/network/_layout',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthLayoutRegisterLazyRoute = AuthLayoutRegisterLazyRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/_layout/register.lazy').then((d) => d.Route),
)
const AuthLayoutLoginLazyRoute = AuthLayoutLoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/_layout/login.lazy').then((d) => d.Route),
)
const AuthLayoutInviteLazyRoute = AuthLayoutInviteLazyRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthLayoutRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/_layout/invite.lazy').then((d) => d.Route),
)
const AppLayoutNotFoundRoute = AppLayoutNotFoundRouteImport.update({
  id: '/$notFound',
  path: '/$notFound',
  getParentRoute: () => AppLayoutRoute,
} as any)
const NetworkLayoutServerIndexRoute =
  NetworkLayoutServerIndexRouteImport.update({
    id: '/server/',
    path: '/server/',
    getParentRoute: () => NetworkLayoutRoute,
  } as any)
const NetworkLayoutClientIndexRoute =
  NetworkLayoutClientIndexRouteImport.update({
    id: '/client/',
    path: '/client/',
    getParentRoute: () => NetworkLayoutRoute,
  } as any)
const AppLayoutSettingsIndexRoute = AppLayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutScheduleIndexRoute = AppLayoutScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutOrdersIndexRoute = AppLayoutOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutNotificationsIndexRoute =
  AppLayoutNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutMeIndexRoute = AppLayoutMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutLogoutIndexRoute = AppLayoutLogoutIndexRouteImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutEmployeesIndexRoute = AppLayoutEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutCustomersIndexRoute = AppLayoutCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutBookingsIndexRoute = AppLayoutBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutSettingsSystemIndexRoute =
  AppLayoutSettingsSystemIndexRouteImport.update({
    id: '/settings/system/',
    path: '/settings/system/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutMeSecurityIndexRoute =
  AppLayoutMeSecurityIndexRouteImport.update({
    id: '/me/security/',
    path: '/me/security/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutEmployeesUsersIndexRoute =
  AppLayoutEmployeesUsersIndexRouteImport.update({
    id: '/employees/users/',
    path: '/employees/users/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutCustomersCreateIndexRoute =
  AppLayoutCustomersCreateIndexRouteImport.update({
    id: '/customers/create/',
    path: '/customers/create/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutCustomersCustomer_idIndexRoute =
  AppLayoutCustomersCustomer_idIndexRouteImport.update({
    id: '/customers/$customer_id/',
    path: '/customers/$customer_id/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutCompanyCreateIndexRoute =
  AppLayoutCompanyCreateIndexRouteImport.update({
    id: '/company/create/',
    path: '/company/create/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBusinessServicesIndexRoute =
  AppLayoutBusinessServicesIndexRouteImport.update({
    id: '/business/services/',
    path: '/business/services/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBusinessLocationsIndexRoute =
  AppLayoutBusinessLocationsIndexRouteImport.update({
    id: '/business/locations/',
    path: '/business/locations/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBookingsCreateIndexRoute =
  AppLayoutBookingsCreateIndexRouteImport.update({
    id: '/bookings/create/',
    path: '/bookings/create/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBookingsBooking_idIndexRoute =
  AppLayoutBookingsBooking_idIndexRouteImport.update({
    id: '/bookings/$booking_id/',
    path: '/bookings/$booking_id/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutEmployeesScheduleEmployee_idRoute =
  AppLayoutEmployeesScheduleEmployee_idRouteImport.update({
    id: '/employees/schedule/$employee_id',
    path: '/employees/schedule/$employee_id',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutEmployeesUsersCreateIndexRoute =
  AppLayoutEmployeesUsersCreateIndexRouteImport.update({
    id: '/employees/users/create/',
    path: '/employees/users/create/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutEmployeesUsersEmployee_idIndexRoute =
  AppLayoutEmployeesUsersEmployee_idIndexRouteImport.update({
    id: '/employees/users/$employee_id/',
    path: '/employees/users/$employee_id/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBusinessServicesCreateIndexRoute =
  AppLayoutBusinessServicesCreateIndexRouteImport.update({
    id: '/business/services/create/',
    path: '/business/services/create/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBusinessServicesService_idIndexRoute =
  AppLayoutBusinessServicesService_idIndexRouteImport.update({
    id: '/business/services/$service_id/',
    path: '/business/services/$service_id/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBusinessLocationsCreateIndexRoute =
  AppLayoutBusinessLocationsCreateIndexRouteImport.update({
    id: '/business/locations/create/',
    path: '/business/locations/create/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBookingsBooking_idResultIndexRoute =
  AppLayoutBookingsBooking_idResultIndexRouteImport.update({
    id: '/bookings/$booking_id/result/',
    path: '/bookings/$booking_id/result/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBookingsBooking_idEditIndexRoute =
  AppLayoutBookingsBooking_idEditIndexRouteImport.update({
    id: '/bookings/$booking_id/edit/',
    path: '/bookings/$booking_id/edit/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBookingsBooking_idCheckoutIndexRoute =
  AppLayoutBookingsBooking_idCheckoutIndexRouteImport.update({
    id: '/bookings/$booking_id/checkout/',
    path: '/bookings/$booking_id/checkout/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutEmployeesUsersEmployee_idServicesIndexRoute =
  AppLayoutEmployeesUsersEmployee_idServicesIndexRouteImport.update({
    id: '/employees/users/$employee_id/services/',
    path: '/employees/users/$employee_id/services/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutEmployeesUsersEmployee_idPasswordIndexRoute =
  AppLayoutEmployeesUsersEmployee_idPasswordIndexRouteImport.update({
    id: '/employees/users/$employee_id/password/',
    path: '/employees/users/$employee_id/password/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutEmployeesUsersEmployee_idEditIndexRoute =
  AppLayoutEmployeesUsersEmployee_idEditIndexRouteImport.update({
    id: '/employees/users/$employee_id/edit/',
    path: '/employees/users/$employee_id/edit/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBusinessServicesService_idLocationsIndexRoute =
  AppLayoutBusinessServicesService_idLocationsIndexRouteImport.update({
    id: '/business/services/$service_id/locations/',
    path: '/business/services/$service_id/locations/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBusinessServicesService_idEmployeesIndexRoute =
  AppLayoutBusinessServicesService_idEmployeesIndexRouteImport.update({
    id: '/business/services/$service_id/employees/',
    path: '/business/services/$service_id/employees/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBusinessServicesService_idEditIndexRoute =
  AppLayoutBusinessServicesService_idEditIndexRouteImport.update({
    id: '/business/services/$service_id/edit/',
    path: '/business/services/$service_id/edit/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBusinessLocationsLocationLocation_idIndexRoute =
  AppLayoutBusinessLocationsLocationLocation_idIndexRouteImport.update({
    id: '/business/locations/_location/$location_id/',
    path: '/business/locations/$location_id/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBusinessLocationsLocationLocation_idEditIndexRoute =
  AppLayoutBusinessLocationsLocationLocation_idEditIndexRouteImport.update({
    id: '/business/locations/_location/$location_id/edit/',
    path: '/business/locations/$location_id/edit/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppLayoutIndexRoute
  '/network': typeof NetworkLayoutRouteWithChildren
  '/$notFound': typeof AppLayoutNotFoundRoute
  '/invite': typeof AuthLayoutInviteLazyRoute
  '/login': typeof AuthLayoutLoginLazyRoute
  '/register': typeof AuthLayoutRegisterLazyRoute
  '/bookings/': typeof AppLayoutBookingsIndexRoute
  '/customers/': typeof AppLayoutCustomersIndexRoute
  '/employees/': typeof AppLayoutEmployeesIndexRoute
  '/logout/': typeof AppLayoutLogoutIndexRoute
  '/me/': typeof AppLayoutMeIndexRoute
  '/notifications/': typeof AppLayoutNotificationsIndexRoute
  '/orders/': typeof AppLayoutOrdersIndexRoute
  '/schedule/': typeof AppLayoutScheduleIndexRoute
  '/settings/': typeof AppLayoutSettingsIndexRoute
  '/network/client/': typeof NetworkLayoutClientIndexRoute
  '/network/server/': typeof NetworkLayoutServerIndexRoute
  '/employees/schedule/$employee_id': typeof AppLayoutEmployeesScheduleEmployee_idRoute
  '/bookings/$booking_id/': typeof AppLayoutBookingsBooking_idIndexRoute
  '/bookings/create/': typeof AppLayoutBookingsCreateIndexRoute
  '/business/locations/': typeof AppLayoutBusinessLocationsIndexRoute
  '/business/services/': typeof AppLayoutBusinessServicesIndexRoute
  '/company/create/': typeof AppLayoutCompanyCreateIndexRoute
  '/customers/$customer_id/': typeof AppLayoutCustomersCustomer_idIndexRoute
  '/customers/create/': typeof AppLayoutCustomersCreateIndexRoute
  '/employees/users/': typeof AppLayoutEmployeesUsersIndexRoute
  '/me/security/': typeof AppLayoutMeSecurityIndexRoute
  '/settings/system/': typeof AppLayoutSettingsSystemIndexRoute
  '/bookings/$booking_id/checkout/': typeof AppLayoutBookingsBooking_idCheckoutIndexRoute
  '/bookings/$booking_id/edit/': typeof AppLayoutBookingsBooking_idEditIndexRoute
  '/bookings/$booking_id/result/': typeof AppLayoutBookingsBooking_idResultIndexRoute
  '/business/locations/create/': typeof AppLayoutBusinessLocationsCreateIndexRoute
  '/business/services/$service_id/': typeof AppLayoutBusinessServicesService_idIndexRoute
  '/business/services/create/': typeof AppLayoutBusinessServicesCreateIndexRoute
  '/employees/users/$employee_id/': typeof AppLayoutEmployeesUsersEmployee_idIndexRoute
  '/employees/users/create/': typeof AppLayoutEmployeesUsersCreateIndexRoute
  '/business/locations/$location_id/': typeof AppLayoutBusinessLocationsLocationLocation_idIndexRoute
  '/business/services/$service_id/edit/': typeof AppLayoutBusinessServicesService_idEditIndexRoute
  '/business/services/$service_id/employees/': typeof AppLayoutBusinessServicesService_idEmployeesIndexRoute
  '/business/services/$service_id/locations/': typeof AppLayoutBusinessServicesService_idLocationsIndexRoute
  '/employees/users/$employee_id/edit/': typeof AppLayoutEmployeesUsersEmployee_idEditIndexRoute
  '/employees/users/$employee_id/password/': typeof AppLayoutEmployeesUsersEmployee_idPasswordIndexRoute
  '/employees/users/$employee_id/services/': typeof AppLayoutEmployeesUsersEmployee_idServicesIndexRoute
  '/business/locations/$location_id/edit/': typeof AppLayoutBusinessLocationsLocationLocation_idEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppLayoutIndexRoute
  '/network': typeof NetworkLayoutRouteWithChildren
  '/$notFound': typeof AppLayoutNotFoundRoute
  '/invite': typeof AuthLayoutInviteLazyRoute
  '/login': typeof AuthLayoutLoginLazyRoute
  '/register': typeof AuthLayoutRegisterLazyRoute
  '/bookings': typeof AppLayoutBookingsIndexRoute
  '/customers': typeof AppLayoutCustomersIndexRoute
  '/employees': typeof AppLayoutEmployeesIndexRoute
  '/logout': typeof AppLayoutLogoutIndexRoute
  '/me': typeof AppLayoutMeIndexRoute
  '/notifications': typeof AppLayoutNotificationsIndexRoute
  '/orders': typeof AppLayoutOrdersIndexRoute
  '/schedule': typeof AppLayoutScheduleIndexRoute
  '/settings': typeof AppLayoutSettingsIndexRoute
  '/network/client': typeof NetworkLayoutClientIndexRoute
  '/network/server': typeof NetworkLayoutServerIndexRoute
  '/employees/schedule/$employee_id': typeof AppLayoutEmployeesScheduleEmployee_idRoute
  '/bookings/$booking_id': typeof AppLayoutBookingsBooking_idIndexRoute
  '/bookings/create': typeof AppLayoutBookingsCreateIndexRoute
  '/business/locations': typeof AppLayoutBusinessLocationsIndexRoute
  '/business/services': typeof AppLayoutBusinessServicesIndexRoute
  '/company/create': typeof AppLayoutCompanyCreateIndexRoute
  '/customers/$customer_id': typeof AppLayoutCustomersCustomer_idIndexRoute
  '/customers/create': typeof AppLayoutCustomersCreateIndexRoute
  '/employees/users': typeof AppLayoutEmployeesUsersIndexRoute
  '/me/security': typeof AppLayoutMeSecurityIndexRoute
  '/settings/system': typeof AppLayoutSettingsSystemIndexRoute
  '/bookings/$booking_id/checkout': typeof AppLayoutBookingsBooking_idCheckoutIndexRoute
  '/bookings/$booking_id/edit': typeof AppLayoutBookingsBooking_idEditIndexRoute
  '/bookings/$booking_id/result': typeof AppLayoutBookingsBooking_idResultIndexRoute
  '/business/locations/create': typeof AppLayoutBusinessLocationsCreateIndexRoute
  '/business/services/$service_id': typeof AppLayoutBusinessServicesService_idIndexRoute
  '/business/services/create': typeof AppLayoutBusinessServicesCreateIndexRoute
  '/employees/users/$employee_id': typeof AppLayoutEmployeesUsersEmployee_idIndexRoute
  '/employees/users/create': typeof AppLayoutEmployeesUsersCreateIndexRoute
  '/business/locations/$location_id': typeof AppLayoutBusinessLocationsLocationLocation_idIndexRoute
  '/business/services/$service_id/edit': typeof AppLayoutBusinessServicesService_idEditIndexRoute
  '/business/services/$service_id/employees': typeof AppLayoutBusinessServicesService_idEmployeesIndexRoute
  '/business/services/$service_id/locations': typeof AppLayoutBusinessServicesService_idLocationsIndexRoute
  '/employees/users/$employee_id/edit': typeof AppLayoutEmployeesUsersEmployee_idEditIndexRoute
  '/employees/users/$employee_id/password': typeof AppLayoutEmployeesUsersEmployee_idPasswordIndexRoute
  '/employees/users/$employee_id/services': typeof AppLayoutEmployeesUsersEmployee_idServicesIndexRoute
  '/business/locations/$location_id/edit': typeof AppLayoutBusinessLocationsLocationLocation_idEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/_layout': typeof AppLayoutRouteWithChildren
  '/_auth/_layout': typeof AuthLayoutRouteWithChildren
  '/network/_layout': typeof NetworkLayoutRouteWithChildren
  '/_app/_layout/$notFound': typeof AppLayoutNotFoundRoute
  '/_auth/_layout/invite': typeof AuthLayoutInviteLazyRoute
  '/_auth/_layout/login': typeof AuthLayoutLoginLazyRoute
  '/_auth/_layout/register': typeof AuthLayoutRegisterLazyRoute
  '/_app/_layout/': typeof AppLayoutIndexRoute
  '/_app/_layout/bookings/': typeof AppLayoutBookingsIndexRoute
  '/_app/_layout/customers/': typeof AppLayoutCustomersIndexRoute
  '/_app/_layout/employees/': typeof AppLayoutEmployeesIndexRoute
  '/_app/_layout/logout/': typeof AppLayoutLogoutIndexRoute
  '/_app/_layout/me/': typeof AppLayoutMeIndexRoute
  '/_app/_layout/notifications/': typeof AppLayoutNotificationsIndexRoute
  '/_app/_layout/orders/': typeof AppLayoutOrdersIndexRoute
  '/_app/_layout/schedule/': typeof AppLayoutScheduleIndexRoute
  '/_app/_layout/settings/': typeof AppLayoutSettingsIndexRoute
  '/network/_layout/client/': typeof NetworkLayoutClientIndexRoute
  '/network/_layout/server/': typeof NetworkLayoutServerIndexRoute
  '/_app/_layout/employees/schedule/$employee_id': typeof AppLayoutEmployeesScheduleEmployee_idRoute
  '/_app/_layout/bookings/$booking_id/': typeof AppLayoutBookingsBooking_idIndexRoute
  '/_app/_layout/bookings/create/': typeof AppLayoutBookingsCreateIndexRoute
  '/_app/_layout/business/locations/': typeof AppLayoutBusinessLocationsIndexRoute
  '/_app/_layout/business/services/': typeof AppLayoutBusinessServicesIndexRoute
  '/_app/_layout/company/create/': typeof AppLayoutCompanyCreateIndexRoute
  '/_app/_layout/customers/$customer_id/': typeof AppLayoutCustomersCustomer_idIndexRoute
  '/_app/_layout/customers/create/': typeof AppLayoutCustomersCreateIndexRoute
  '/_app/_layout/employees/users/': typeof AppLayoutEmployeesUsersIndexRoute
  '/_app/_layout/me/security/': typeof AppLayoutMeSecurityIndexRoute
  '/_app/_layout/settings/system/': typeof AppLayoutSettingsSystemIndexRoute
  '/_app/_layout/bookings/$booking_id/checkout/': typeof AppLayoutBookingsBooking_idCheckoutIndexRoute
  '/_app/_layout/bookings/$booking_id/edit/': typeof AppLayoutBookingsBooking_idEditIndexRoute
  '/_app/_layout/bookings/$booking_id/result/': typeof AppLayoutBookingsBooking_idResultIndexRoute
  '/_app/_layout/business/locations/create/': typeof AppLayoutBusinessLocationsCreateIndexRoute
  '/_app/_layout/business/services/$service_id/': typeof AppLayoutBusinessServicesService_idIndexRoute
  '/_app/_layout/business/services/create/': typeof AppLayoutBusinessServicesCreateIndexRoute
  '/_app/_layout/employees/users/$employee_id/': typeof AppLayoutEmployeesUsersEmployee_idIndexRoute
  '/_app/_layout/employees/users/create/': typeof AppLayoutEmployeesUsersCreateIndexRoute
  '/_app/_layout/business/locations/_location/$location_id/': typeof AppLayoutBusinessLocationsLocationLocation_idIndexRoute
  '/_app/_layout/business/services/$service_id/edit/': typeof AppLayoutBusinessServicesService_idEditIndexRoute
  '/_app/_layout/business/services/$service_id/employees/': typeof AppLayoutBusinessServicesService_idEmployeesIndexRoute
  '/_app/_layout/business/services/$service_id/locations/': typeof AppLayoutBusinessServicesService_idLocationsIndexRoute
  '/_app/_layout/employees/users/$employee_id/edit/': typeof AppLayoutEmployeesUsersEmployee_idEditIndexRoute
  '/_app/_layout/employees/users/$employee_id/password/': typeof AppLayoutEmployeesUsersEmployee_idPasswordIndexRoute
  '/_app/_layout/employees/users/$employee_id/services/': typeof AppLayoutEmployeesUsersEmployee_idServicesIndexRoute
  '/_app/_layout/business/locations/_location/$location_id/edit/': typeof AppLayoutBusinessLocationsLocationLocation_idEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/network'
    | '/$notFound'
    | '/invite'
    | '/login'
    | '/register'
    | '/bookings/'
    | '/customers/'
    | '/employees/'
    | '/logout/'
    | '/me/'
    | '/notifications/'
    | '/orders/'
    | '/schedule/'
    | '/settings/'
    | '/network/client/'
    | '/network/server/'
    | '/employees/schedule/$employee_id'
    | '/bookings/$booking_id/'
    | '/bookings/create/'
    | '/business/locations/'
    | '/business/services/'
    | '/company/create/'
    | '/customers/$customer_id/'
    | '/customers/create/'
    | '/employees/users/'
    | '/me/security/'
    | '/settings/system/'
    | '/bookings/$booking_id/checkout/'
    | '/bookings/$booking_id/edit/'
    | '/bookings/$booking_id/result/'
    | '/business/locations/create/'
    | '/business/services/$service_id/'
    | '/business/services/create/'
    | '/employees/users/$employee_id/'
    | '/employees/users/create/'
    | '/business/locations/$location_id/'
    | '/business/services/$service_id/edit/'
    | '/business/services/$service_id/employees/'
    | '/business/services/$service_id/locations/'
    | '/employees/users/$employee_id/edit/'
    | '/employees/users/$employee_id/password/'
    | '/employees/users/$employee_id/services/'
    | '/business/locations/$location_id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/network'
    | '/$notFound'
    | '/invite'
    | '/login'
    | '/register'
    | '/bookings'
    | '/customers'
    | '/employees'
    | '/logout'
    | '/me'
    | '/notifications'
    | '/orders'
    | '/schedule'
    | '/settings'
    | '/network/client'
    | '/network/server'
    | '/employees/schedule/$employee_id'
    | '/bookings/$booking_id'
    | '/bookings/create'
    | '/business/locations'
    | '/business/services'
    | '/company/create'
    | '/customers/$customer_id'
    | '/customers/create'
    | '/employees/users'
    | '/me/security'
    | '/settings/system'
    | '/bookings/$booking_id/checkout'
    | '/bookings/$booking_id/edit'
    | '/bookings/$booking_id/result'
    | '/business/locations/create'
    | '/business/services/$service_id'
    | '/business/services/create'
    | '/employees/users/$employee_id'
    | '/employees/users/create'
    | '/business/locations/$location_id'
    | '/business/services/$service_id/edit'
    | '/business/services/$service_id/employees'
    | '/business/services/$service_id/locations'
    | '/employees/users/$employee_id/edit'
    | '/employees/users/$employee_id/password'
    | '/employees/users/$employee_id/services'
    | '/business/locations/$location_id/edit'
  id:
    | '__root__'
    | '/_app/_layout'
    | '/_auth/_layout'
    | '/network/_layout'
    | '/_app/_layout/$notFound'
    | '/_auth/_layout/invite'
    | '/_auth/_layout/login'
    | '/_auth/_layout/register'
    | '/_app/_layout/'
    | '/_app/_layout/bookings/'
    | '/_app/_layout/customers/'
    | '/_app/_layout/employees/'
    | '/_app/_layout/logout/'
    | '/_app/_layout/me/'
    | '/_app/_layout/notifications/'
    | '/_app/_layout/orders/'
    | '/_app/_layout/schedule/'
    | '/_app/_layout/settings/'
    | '/network/_layout/client/'
    | '/network/_layout/server/'
    | '/_app/_layout/employees/schedule/$employee_id'
    | '/_app/_layout/bookings/$booking_id/'
    | '/_app/_layout/bookings/create/'
    | '/_app/_layout/business/locations/'
    | '/_app/_layout/business/services/'
    | '/_app/_layout/company/create/'
    | '/_app/_layout/customers/$customer_id/'
    | '/_app/_layout/customers/create/'
    | '/_app/_layout/employees/users/'
    | '/_app/_layout/me/security/'
    | '/_app/_layout/settings/system/'
    | '/_app/_layout/bookings/$booking_id/checkout/'
    | '/_app/_layout/bookings/$booking_id/edit/'
    | '/_app/_layout/bookings/$booking_id/result/'
    | '/_app/_layout/business/locations/create/'
    | '/_app/_layout/business/services/$service_id/'
    | '/_app/_layout/business/services/create/'
    | '/_app/_layout/employees/users/$employee_id/'
    | '/_app/_layout/employees/users/create/'
    | '/_app/_layout/business/locations/_location/$location_id/'
    | '/_app/_layout/business/services/$service_id/edit/'
    | '/_app/_layout/business/services/$service_id/employees/'
    | '/_app/_layout/business/services/$service_id/locations/'
    | '/_app/_layout/employees/users/$employee_id/edit/'
    | '/_app/_layout/employees/users/$employee_id/password/'
    | '/_app/_layout/employees/users/$employee_id/services/'
    | '/_app/_layout/business/locations/_location/$location_id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  NetworkLayoutRoute: typeof NetworkLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/network/_layout': {
      id: '/network/_layout'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_layout': {
      id: '/_auth/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_layout': {
      id: '/_app/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_layout/': {
      id: '/_app/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/_layout/register': {
      id: '/_auth/_layout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthLayoutRegisterLazyRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/login': {
      id: '/_auth/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginLazyRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/invite': {
      id: '/_auth/_layout/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthLayoutInviteLazyRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/_layout/$notFound': {
      id: '/_app/_layout/$notFound'
      path: '/$notFound'
      fullPath: '/$notFound'
      preLoaderRoute: typeof AppLayoutNotFoundRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/network/_layout/server/': {
      id: '/network/_layout/server/'
      path: '/server'
      fullPath: '/network/server/'
      preLoaderRoute: typeof NetworkLayoutServerIndexRouteImport
      parentRoute: typeof NetworkLayoutRoute
    }
    '/network/_layout/client/': {
      id: '/network/_layout/client/'
      path: '/client'
      fullPath: '/network/client/'
      preLoaderRoute: typeof NetworkLayoutClientIndexRouteImport
      parentRoute: typeof NetworkLayoutRoute
    }
    '/_app/_layout/settings/': {
      id: '/_app/_layout/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppLayoutSettingsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/schedule/': {
      id: '/_app/_layout/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof AppLayoutScheduleIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/orders/': {
      id: '/_app/_layout/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppLayoutOrdersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/notifications/': {
      id: '/_app/_layout/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AppLayoutNotificationsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/me/': {
      id: '/_app/_layout/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof AppLayoutMeIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/logout/': {
      id: '/_app/_layout/logout/'
      path: '/logout'
      fullPath: '/logout/'
      preLoaderRoute: typeof AppLayoutLogoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/employees/': {
      id: '/_app/_layout/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AppLayoutEmployeesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/customers/': {
      id: '/_app/_layout/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppLayoutCustomersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/bookings/': {
      id: '/_app/_layout/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AppLayoutBookingsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/settings/system/': {
      id: '/_app/_layout/settings/system/'
      path: '/settings/system'
      fullPath: '/settings/system/'
      preLoaderRoute: typeof AppLayoutSettingsSystemIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/me/security/': {
      id: '/_app/_layout/me/security/'
      path: '/me/security'
      fullPath: '/me/security/'
      preLoaderRoute: typeof AppLayoutMeSecurityIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/employees/users/': {
      id: '/_app/_layout/employees/users/'
      path: '/employees/users'
      fullPath: '/employees/users/'
      preLoaderRoute: typeof AppLayoutEmployeesUsersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/customers/create/': {
      id: '/_app/_layout/customers/create/'
      path: '/customers/create'
      fullPath: '/customers/create/'
      preLoaderRoute: typeof AppLayoutCustomersCreateIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/customers/$customer_id/': {
      id: '/_app/_layout/customers/$customer_id/'
      path: '/customers/$customer_id'
      fullPath: '/customers/$customer_id/'
      preLoaderRoute: typeof AppLayoutCustomersCustomer_idIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/company/create/': {
      id: '/_app/_layout/company/create/'
      path: '/company/create'
      fullPath: '/company/create/'
      preLoaderRoute: typeof AppLayoutCompanyCreateIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/business/services/': {
      id: '/_app/_layout/business/services/'
      path: '/business/services'
      fullPath: '/business/services/'
      preLoaderRoute: typeof AppLayoutBusinessServicesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/business/locations/': {
      id: '/_app/_layout/business/locations/'
      path: '/business/locations'
      fullPath: '/business/locations/'
      preLoaderRoute: typeof AppLayoutBusinessLocationsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/bookings/create/': {
      id: '/_app/_layout/bookings/create/'
      path: '/bookings/create'
      fullPath: '/bookings/create/'
      preLoaderRoute: typeof AppLayoutBookingsCreateIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/bookings/$booking_id/': {
      id: '/_app/_layout/bookings/$booking_id/'
      path: '/bookings/$booking_id'
      fullPath: '/bookings/$booking_id/'
      preLoaderRoute: typeof AppLayoutBookingsBooking_idIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/employees/schedule/$employee_id': {
      id: '/_app/_layout/employees/schedule/$employee_id'
      path: '/employees/schedule/$employee_id'
      fullPath: '/employees/schedule/$employee_id'
      preLoaderRoute: typeof AppLayoutEmployeesScheduleEmployee_idRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/employees/users/create/': {
      id: '/_app/_layout/employees/users/create/'
      path: '/employees/users/create'
      fullPath: '/employees/users/create/'
      preLoaderRoute: typeof AppLayoutEmployeesUsersCreateIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/employees/users/$employee_id/': {
      id: '/_app/_layout/employees/users/$employee_id/'
      path: '/employees/users/$employee_id'
      fullPath: '/employees/users/$employee_id/'
      preLoaderRoute: typeof AppLayoutEmployeesUsersEmployee_idIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/business/services/create/': {
      id: '/_app/_layout/business/services/create/'
      path: '/business/services/create'
      fullPath: '/business/services/create/'
      preLoaderRoute: typeof AppLayoutBusinessServicesCreateIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/business/services/$service_id/': {
      id: '/_app/_layout/business/services/$service_id/'
      path: '/business/services/$service_id'
      fullPath: '/business/services/$service_id/'
      preLoaderRoute: typeof AppLayoutBusinessServicesService_idIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/business/locations/create/': {
      id: '/_app/_layout/business/locations/create/'
      path: '/business/locations/create'
      fullPath: '/business/locations/create/'
      preLoaderRoute: typeof AppLayoutBusinessLocationsCreateIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/bookings/$booking_id/result/': {
      id: '/_app/_layout/bookings/$booking_id/result/'
      path: '/bookings/$booking_id/result'
      fullPath: '/bookings/$booking_id/result/'
      preLoaderRoute: typeof AppLayoutBookingsBooking_idResultIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/bookings/$booking_id/edit/': {
      id: '/_app/_layout/bookings/$booking_id/edit/'
      path: '/bookings/$booking_id/edit'
      fullPath: '/bookings/$booking_id/edit/'
      preLoaderRoute: typeof AppLayoutBookingsBooking_idEditIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/bookings/$booking_id/checkout/': {
      id: '/_app/_layout/bookings/$booking_id/checkout/'
      path: '/bookings/$booking_id/checkout'
      fullPath: '/bookings/$booking_id/checkout/'
      preLoaderRoute: typeof AppLayoutBookingsBooking_idCheckoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/employees/users/$employee_id/services/': {
      id: '/_app/_layout/employees/users/$employee_id/services/'
      path: '/employees/users/$employee_id/services'
      fullPath: '/employees/users/$employee_id/services/'
      preLoaderRoute: typeof AppLayoutEmployeesUsersEmployee_idServicesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/employees/users/$employee_id/password/': {
      id: '/_app/_layout/employees/users/$employee_id/password/'
      path: '/employees/users/$employee_id/password'
      fullPath: '/employees/users/$employee_id/password/'
      preLoaderRoute: typeof AppLayoutEmployeesUsersEmployee_idPasswordIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/employees/users/$employee_id/edit/': {
      id: '/_app/_layout/employees/users/$employee_id/edit/'
      path: '/employees/users/$employee_id/edit'
      fullPath: '/employees/users/$employee_id/edit/'
      preLoaderRoute: typeof AppLayoutEmployeesUsersEmployee_idEditIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/business/services/$service_id/locations/': {
      id: '/_app/_layout/business/services/$service_id/locations/'
      path: '/business/services/$service_id/locations'
      fullPath: '/business/services/$service_id/locations/'
      preLoaderRoute: typeof AppLayoutBusinessServicesService_idLocationsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/business/services/$service_id/employees/': {
      id: '/_app/_layout/business/services/$service_id/employees/'
      path: '/business/services/$service_id/employees'
      fullPath: '/business/services/$service_id/employees/'
      preLoaderRoute: typeof AppLayoutBusinessServicesService_idEmployeesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/business/services/$service_id/edit/': {
      id: '/_app/_layout/business/services/$service_id/edit/'
      path: '/business/services/$service_id/edit'
      fullPath: '/business/services/$service_id/edit/'
      preLoaderRoute: typeof AppLayoutBusinessServicesService_idEditIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/business/locations/_location/$location_id/': {
      id: '/_app/_layout/business/locations/_location/$location_id/'
      path: '/business/locations/$location_id'
      fullPath: '/business/locations/$location_id/'
      preLoaderRoute: typeof AppLayoutBusinessLocationsLocationLocation_idIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/business/locations/_location/$location_id/edit/': {
      id: '/_app/_layout/business/locations/_location/$location_id/edit/'
      path: '/business/locations/$location_id/edit'
      fullPath: '/business/locations/$location_id/edit/'
      preLoaderRoute: typeof AppLayoutBusinessLocationsLocationLocation_idEditIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppLayoutNotFoundRoute: typeof AppLayoutNotFoundRoute
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
  AppLayoutBookingsIndexRoute: typeof AppLayoutBookingsIndexRoute
  AppLayoutCustomersIndexRoute: typeof AppLayoutCustomersIndexRoute
  AppLayoutEmployeesIndexRoute: typeof AppLayoutEmployeesIndexRoute
  AppLayoutLogoutIndexRoute: typeof AppLayoutLogoutIndexRoute
  AppLayoutMeIndexRoute: typeof AppLayoutMeIndexRoute
  AppLayoutNotificationsIndexRoute: typeof AppLayoutNotificationsIndexRoute
  AppLayoutOrdersIndexRoute: typeof AppLayoutOrdersIndexRoute
  AppLayoutScheduleIndexRoute: typeof AppLayoutScheduleIndexRoute
  AppLayoutSettingsIndexRoute: typeof AppLayoutSettingsIndexRoute
  AppLayoutEmployeesScheduleEmployee_idRoute: typeof AppLayoutEmployeesScheduleEmployee_idRoute
  AppLayoutBookingsBooking_idIndexRoute: typeof AppLayoutBookingsBooking_idIndexRoute
  AppLayoutBookingsCreateIndexRoute: typeof AppLayoutBookingsCreateIndexRoute
  AppLayoutBusinessLocationsIndexRoute: typeof AppLayoutBusinessLocationsIndexRoute
  AppLayoutBusinessServicesIndexRoute: typeof AppLayoutBusinessServicesIndexRoute
  AppLayoutCompanyCreateIndexRoute: typeof AppLayoutCompanyCreateIndexRoute
  AppLayoutCustomersCustomer_idIndexRoute: typeof AppLayoutCustomersCustomer_idIndexRoute
  AppLayoutCustomersCreateIndexRoute: typeof AppLayoutCustomersCreateIndexRoute
  AppLayoutEmployeesUsersIndexRoute: typeof AppLayoutEmployeesUsersIndexRoute
  AppLayoutMeSecurityIndexRoute: typeof AppLayoutMeSecurityIndexRoute
  AppLayoutSettingsSystemIndexRoute: typeof AppLayoutSettingsSystemIndexRoute
  AppLayoutBookingsBooking_idCheckoutIndexRoute: typeof AppLayoutBookingsBooking_idCheckoutIndexRoute
  AppLayoutBookingsBooking_idEditIndexRoute: typeof AppLayoutBookingsBooking_idEditIndexRoute
  AppLayoutBookingsBooking_idResultIndexRoute: typeof AppLayoutBookingsBooking_idResultIndexRoute
  AppLayoutBusinessLocationsCreateIndexRoute: typeof AppLayoutBusinessLocationsCreateIndexRoute
  AppLayoutBusinessServicesService_idIndexRoute: typeof AppLayoutBusinessServicesService_idIndexRoute
  AppLayoutBusinessServicesCreateIndexRoute: typeof AppLayoutBusinessServicesCreateIndexRoute
  AppLayoutEmployeesUsersEmployee_idIndexRoute: typeof AppLayoutEmployeesUsersEmployee_idIndexRoute
  AppLayoutEmployeesUsersCreateIndexRoute: typeof AppLayoutEmployeesUsersCreateIndexRoute
  AppLayoutBusinessLocationsLocationLocation_idIndexRoute: typeof AppLayoutBusinessLocationsLocationLocation_idIndexRoute
  AppLayoutBusinessServicesService_idEditIndexRoute: typeof AppLayoutBusinessServicesService_idEditIndexRoute
  AppLayoutBusinessServicesService_idEmployeesIndexRoute: typeof AppLayoutBusinessServicesService_idEmployeesIndexRoute
  AppLayoutBusinessServicesService_idLocationsIndexRoute: typeof AppLayoutBusinessServicesService_idLocationsIndexRoute
  AppLayoutEmployeesUsersEmployee_idEditIndexRoute: typeof AppLayoutEmployeesUsersEmployee_idEditIndexRoute
  AppLayoutEmployeesUsersEmployee_idPasswordIndexRoute: typeof AppLayoutEmployeesUsersEmployee_idPasswordIndexRoute
  AppLayoutEmployeesUsersEmployee_idServicesIndexRoute: typeof AppLayoutEmployeesUsersEmployee_idServicesIndexRoute
  AppLayoutBusinessLocationsLocationLocation_idEditIndexRoute: typeof AppLayoutBusinessLocationsLocationLocation_idEditIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutNotFoundRoute: AppLayoutNotFoundRoute,
  AppLayoutIndexRoute: AppLayoutIndexRoute,
  AppLayoutBookingsIndexRoute: AppLayoutBookingsIndexRoute,
  AppLayoutCustomersIndexRoute: AppLayoutCustomersIndexRoute,
  AppLayoutEmployeesIndexRoute: AppLayoutEmployeesIndexRoute,
  AppLayoutLogoutIndexRoute: AppLayoutLogoutIndexRoute,
  AppLayoutMeIndexRoute: AppLayoutMeIndexRoute,
  AppLayoutNotificationsIndexRoute: AppLayoutNotificationsIndexRoute,
  AppLayoutOrdersIndexRoute: AppLayoutOrdersIndexRoute,
  AppLayoutScheduleIndexRoute: AppLayoutScheduleIndexRoute,
  AppLayoutSettingsIndexRoute: AppLayoutSettingsIndexRoute,
  AppLayoutEmployeesScheduleEmployee_idRoute:
    AppLayoutEmployeesScheduleEmployee_idRoute,
  AppLayoutBookingsBooking_idIndexRoute: AppLayoutBookingsBooking_idIndexRoute,
  AppLayoutBookingsCreateIndexRoute: AppLayoutBookingsCreateIndexRoute,
  AppLayoutBusinessLocationsIndexRoute: AppLayoutBusinessLocationsIndexRoute,
  AppLayoutBusinessServicesIndexRoute: AppLayoutBusinessServicesIndexRoute,
  AppLayoutCompanyCreateIndexRoute: AppLayoutCompanyCreateIndexRoute,
  AppLayoutCustomersCustomer_idIndexRoute:
    AppLayoutCustomersCustomer_idIndexRoute,
  AppLayoutCustomersCreateIndexRoute: AppLayoutCustomersCreateIndexRoute,
  AppLayoutEmployeesUsersIndexRoute: AppLayoutEmployeesUsersIndexRoute,
  AppLayoutMeSecurityIndexRoute: AppLayoutMeSecurityIndexRoute,
  AppLayoutSettingsSystemIndexRoute: AppLayoutSettingsSystemIndexRoute,
  AppLayoutBookingsBooking_idCheckoutIndexRoute:
    AppLayoutBookingsBooking_idCheckoutIndexRoute,
  AppLayoutBookingsBooking_idEditIndexRoute:
    AppLayoutBookingsBooking_idEditIndexRoute,
  AppLayoutBookingsBooking_idResultIndexRoute:
    AppLayoutBookingsBooking_idResultIndexRoute,
  AppLayoutBusinessLocationsCreateIndexRoute:
    AppLayoutBusinessLocationsCreateIndexRoute,
  AppLayoutBusinessServicesService_idIndexRoute:
    AppLayoutBusinessServicesService_idIndexRoute,
  AppLayoutBusinessServicesCreateIndexRoute:
    AppLayoutBusinessServicesCreateIndexRoute,
  AppLayoutEmployeesUsersEmployee_idIndexRoute:
    AppLayoutEmployeesUsersEmployee_idIndexRoute,
  AppLayoutEmployeesUsersCreateIndexRoute:
    AppLayoutEmployeesUsersCreateIndexRoute,
  AppLayoutBusinessLocationsLocationLocation_idIndexRoute:
    AppLayoutBusinessLocationsLocationLocation_idIndexRoute,
  AppLayoutBusinessServicesService_idEditIndexRoute:
    AppLayoutBusinessServicesService_idEditIndexRoute,
  AppLayoutBusinessServicesService_idEmployeesIndexRoute:
    AppLayoutBusinessServicesService_idEmployeesIndexRoute,
  AppLayoutBusinessServicesService_idLocationsIndexRoute:
    AppLayoutBusinessServicesService_idLocationsIndexRoute,
  AppLayoutEmployeesUsersEmployee_idEditIndexRoute:
    AppLayoutEmployeesUsersEmployee_idEditIndexRoute,
  AppLayoutEmployeesUsersEmployee_idPasswordIndexRoute:
    AppLayoutEmployeesUsersEmployee_idPasswordIndexRoute,
  AppLayoutEmployeesUsersEmployee_idServicesIndexRoute:
    AppLayoutEmployeesUsersEmployee_idServicesIndexRoute,
  AppLayoutBusinessLocationsLocationLocation_idEditIndexRoute:
    AppLayoutBusinessLocationsLocationLocation_idEditIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLayoutInviteLazyRoute: typeof AuthLayoutInviteLazyRoute
  AuthLayoutLoginLazyRoute: typeof AuthLayoutLoginLazyRoute
  AuthLayoutRegisterLazyRoute: typeof AuthLayoutRegisterLazyRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutInviteLazyRoute: AuthLayoutInviteLazyRoute,
  AuthLayoutLoginLazyRoute: AuthLayoutLoginLazyRoute,
  AuthLayoutRegisterLazyRoute: AuthLayoutRegisterLazyRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface NetworkLayoutRouteChildren {
  NetworkLayoutClientIndexRoute: typeof NetworkLayoutClientIndexRoute
  NetworkLayoutServerIndexRoute: typeof NetworkLayoutServerIndexRoute
}

const NetworkLayoutRouteChildren: NetworkLayoutRouteChildren = {
  NetworkLayoutClientIndexRoute: NetworkLayoutClientIndexRoute,
  NetworkLayoutServerIndexRoute: NetworkLayoutServerIndexRoute,
}

const NetworkLayoutRouteWithChildren = NetworkLayoutRoute._addFileChildren(
  NetworkLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  NetworkLayoutRoute: NetworkLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
