/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as NetworkLayoutRouteImport } from './app/routes/network/_layout'
import { Route as AuthLayoutRouteImport } from './app/routes/_auth/_layout'
import { Route as AppLayoutRouteImport } from './app/routes/_app/_layout'
import { Route as AppLayoutIndexRouteImport } from './app/routes/_app/_layout/index'
import { Route as AppLayoutNotFoundRouteImport } from './app/routes/_app/_layout/$notFound'
import { Route as NetworkLayoutServerIndexRouteImport } from './app/routes/network/_layout/server/index'
import { Route as NetworkLayoutClientIndexRouteImport } from './app/routes/network/_layout/client/index'
import { Route as AppLayoutSettingsIndexRouteImport } from './app/routes/_app/_layout/settings/index'
import { Route as AppLayoutScheduleIndexRouteImport } from './app/routes/_app/_layout/schedule/index'
import { Route as AppLayoutNotificationsIndexRouteImport } from './app/routes/_app/_layout/notifications/index'
import { Route as AppLayoutEmployeesIndexRouteImport } from './app/routes/_app/_layout/employees/index'
import { Route as AppLayoutCustomersIndexRouteImport } from './app/routes/_app/_layout/customers/index'
import { Route as AppLayoutCompanyCreateIndexRouteImport } from './app/routes/_app/_layout/company/create/index'
import { Route as AppLayoutBusinessServicesIndexRouteImport } from './app/routes/_app/_layout/business/services/index'
import { Route as AppLayoutBusinessLocationsIndexRouteImport } from './app/routes/_app/_layout/business/locations/index'
import { Route as AppLayoutBusinessLocationsCreateIndexRouteImport } from './app/routes/_app/_layout/business/locations/create/index'
import { Route as AppLayoutBusinessLocationsLocationLocation_idIndexRouteImport } from './app/routes/_app/_layout/business/locations/_location/$location_id/index'
import { Route as AppLayoutBusinessLocationsLocationLocation_idEditIndexRouteImport } from './app/routes/_app/_layout/business/locations/_location/$location_id/edit/index'

const AuthLayoutRegisterLazyRouteImport = createFileRoute(
  '/_auth/_layout/register',
)()
const AuthLayoutLoginLazyRouteImport = createFileRoute('/_auth/_layout/login')()

const NetworkLayoutRoute = NetworkLayoutRouteImport.update({
  id: '/network/_layout',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthLayoutRegisterLazyRoute = AuthLayoutRegisterLazyRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/_layout/register.lazy').then((d) => d.Route),
)
const AuthLayoutLoginLazyRoute = AuthLayoutLoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any).lazy(() =>
  import('./app/routes/_auth/_layout/login.lazy').then((d) => d.Route),
)
const AppLayoutNotFoundRoute = AppLayoutNotFoundRouteImport.update({
  id: '/$notFound',
  path: '/$notFound',
  getParentRoute: () => AppLayoutRoute,
} as any)
const NetworkLayoutServerIndexRoute =
  NetworkLayoutServerIndexRouteImport.update({
    id: '/server/',
    path: '/server/',
    getParentRoute: () => NetworkLayoutRoute,
  } as any)
const NetworkLayoutClientIndexRoute =
  NetworkLayoutClientIndexRouteImport.update({
    id: '/client/',
    path: '/client/',
    getParentRoute: () => NetworkLayoutRoute,
  } as any)
const AppLayoutSettingsIndexRoute = AppLayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutScheduleIndexRoute = AppLayoutScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutNotificationsIndexRoute =
  AppLayoutNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutEmployeesIndexRoute = AppLayoutEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutCustomersIndexRoute = AppLayoutCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutCompanyCreateIndexRoute =
  AppLayoutCompanyCreateIndexRouteImport.update({
    id: '/company/create/',
    path: '/company/create/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBusinessServicesIndexRoute =
  AppLayoutBusinessServicesIndexRouteImport.update({
    id: '/business/services/',
    path: '/business/services/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBusinessLocationsIndexRoute =
  AppLayoutBusinessLocationsIndexRouteImport.update({
    id: '/business/locations/',
    path: '/business/locations/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBusinessLocationsCreateIndexRoute =
  AppLayoutBusinessLocationsCreateIndexRouteImport.update({
    id: '/business/locations/create/',
    path: '/business/locations/create/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBusinessLocationsLocationLocation_idIndexRoute =
  AppLayoutBusinessLocationsLocationLocation_idIndexRouteImport.update({
    id: '/business/locations/_location/$location_id/',
    path: '/business/locations/$location_id/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBusinessLocationsLocationLocation_idEditIndexRoute =
  AppLayoutBusinessLocationsLocationLocation_idEditIndexRouteImport.update({
    id: '/business/locations/_location/$location_id/edit/',
    path: '/business/locations/$location_id/edit/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/network': typeof NetworkLayoutRouteWithChildren
  '/$notFound': typeof AppLayoutNotFoundRoute
  '/login': typeof AuthLayoutLoginLazyRoute
  '/register': typeof AuthLayoutRegisterLazyRoute
  '/': typeof AppLayoutIndexRoute
  '/customers': typeof AppLayoutCustomersIndexRoute
  '/employees': typeof AppLayoutEmployeesIndexRoute
  '/notifications': typeof AppLayoutNotificationsIndexRoute
  '/schedule': typeof AppLayoutScheduleIndexRoute
  '/settings': typeof AppLayoutSettingsIndexRoute
  '/network/client': typeof NetworkLayoutClientIndexRoute
  '/network/server': typeof NetworkLayoutServerIndexRoute
  '/business/locations': typeof AppLayoutBusinessLocationsIndexRoute
  '/business/services': typeof AppLayoutBusinessServicesIndexRoute
  '/company/create': typeof AppLayoutCompanyCreateIndexRoute
  '/business/locations/create': typeof AppLayoutBusinessLocationsCreateIndexRoute
  '/business/locations/$location_id': typeof AppLayoutBusinessLocationsLocationLocation_idIndexRoute
  '/business/locations/$location_id/edit': typeof AppLayoutBusinessLocationsLocationLocation_idEditIndexRoute
}
export interface FileRoutesByTo {
  '/network': typeof NetworkLayoutRouteWithChildren
  '/$notFound': typeof AppLayoutNotFoundRoute
  '/login': typeof AuthLayoutLoginLazyRoute
  '/register': typeof AuthLayoutRegisterLazyRoute
  '/': typeof AppLayoutIndexRoute
  '/customers': typeof AppLayoutCustomersIndexRoute
  '/employees': typeof AppLayoutEmployeesIndexRoute
  '/notifications': typeof AppLayoutNotificationsIndexRoute
  '/schedule': typeof AppLayoutScheduleIndexRoute
  '/settings': typeof AppLayoutSettingsIndexRoute
  '/network/client': typeof NetworkLayoutClientIndexRoute
  '/network/server': typeof NetworkLayoutServerIndexRoute
  '/business/locations': typeof AppLayoutBusinessLocationsIndexRoute
  '/business/services': typeof AppLayoutBusinessServicesIndexRoute
  '/company/create': typeof AppLayoutCompanyCreateIndexRoute
  '/business/locations/create': typeof AppLayoutBusinessLocationsCreateIndexRoute
  '/business/locations/$location_id': typeof AppLayoutBusinessLocationsLocationLocation_idIndexRoute
  '/business/locations/$location_id/edit': typeof AppLayoutBusinessLocationsLocationLocation_idEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/_layout': typeof AppLayoutRouteWithChildren
  '/_auth/_layout': typeof AuthLayoutRouteWithChildren
  '/network/_layout': typeof NetworkLayoutRouteWithChildren
  '/_app/_layout/$notFound': typeof AppLayoutNotFoundRoute
  '/_auth/_layout/login': typeof AuthLayoutLoginLazyRoute
  '/_auth/_layout/register': typeof AuthLayoutRegisterLazyRoute
  '/_app/_layout/': typeof AppLayoutIndexRoute
  '/_app/_layout/customers/': typeof AppLayoutCustomersIndexRoute
  '/_app/_layout/employees/': typeof AppLayoutEmployeesIndexRoute
  '/_app/_layout/notifications/': typeof AppLayoutNotificationsIndexRoute
  '/_app/_layout/schedule/': typeof AppLayoutScheduleIndexRoute
  '/_app/_layout/settings/': typeof AppLayoutSettingsIndexRoute
  '/network/_layout/client/': typeof NetworkLayoutClientIndexRoute
  '/network/_layout/server/': typeof NetworkLayoutServerIndexRoute
  '/_app/_layout/business/locations/': typeof AppLayoutBusinessLocationsIndexRoute
  '/_app/_layout/business/services/': typeof AppLayoutBusinessServicesIndexRoute
  '/_app/_layout/company/create/': typeof AppLayoutCompanyCreateIndexRoute
  '/_app/_layout/business/locations/create/': typeof AppLayoutBusinessLocationsCreateIndexRoute
  '/_app/_layout/business/locations/_location/$location_id/': typeof AppLayoutBusinessLocationsLocationLocation_idIndexRoute
  '/_app/_layout/business/locations/_location/$location_id/edit/': typeof AppLayoutBusinessLocationsLocationLocation_idEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/network'
    | '/$notFound'
    | '/login'
    | '/register'
    | '/'
    | '/customers'
    | '/employees'
    | '/notifications'
    | '/schedule'
    | '/settings'
    | '/network/client'
    | '/network/server'
    | '/business/locations'
    | '/business/services'
    | '/company/create'
    | '/business/locations/create'
    | '/business/locations/$location_id'
    | '/business/locations/$location_id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/network'
    | '/$notFound'
    | '/login'
    | '/register'
    | '/'
    | '/customers'
    | '/employees'
    | '/notifications'
    | '/schedule'
    | '/settings'
    | '/network/client'
    | '/network/server'
    | '/business/locations'
    | '/business/services'
    | '/company/create'
    | '/business/locations/create'
    | '/business/locations/$location_id'
    | '/business/locations/$location_id/edit'
  id:
    | '__root__'
    | '/_app/_layout'
    | '/_auth/_layout'
    | '/network/_layout'
    | '/_app/_layout/$notFound'
    | '/_auth/_layout/login'
    | '/_auth/_layout/register'
    | '/_app/_layout/'
    | '/_app/_layout/customers/'
    | '/_app/_layout/employees/'
    | '/_app/_layout/notifications/'
    | '/_app/_layout/schedule/'
    | '/_app/_layout/settings/'
    | '/network/_layout/client/'
    | '/network/_layout/server/'
    | '/_app/_layout/business/locations/'
    | '/_app/_layout/business/services/'
    | '/_app/_layout/company/create/'
    | '/_app/_layout/business/locations/create/'
    | '/_app/_layout/business/locations/_location/$location_id/'
    | '/_app/_layout/business/locations/_location/$location_id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  NetworkLayoutRoute: typeof NetworkLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/network/_layout': {
      id: '/network/_layout'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_layout': {
      id: '/_auth/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_layout': {
      id: '/_app/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_layout/': {
      id: '/_app/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/_layout/register': {
      id: '/_auth/_layout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthLayoutRegisterLazyRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/login': {
      id: '/_auth/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginLazyRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/_layout/$notFound': {
      id: '/_app/_layout/$notFound'
      path: '/$notFound'
      fullPath: '/$notFound'
      preLoaderRoute: typeof AppLayoutNotFoundRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/network/_layout/server/': {
      id: '/network/_layout/server/'
      path: '/server'
      fullPath: '/network/server'
      preLoaderRoute: typeof NetworkLayoutServerIndexRouteImport
      parentRoute: typeof NetworkLayoutRoute
    }
    '/network/_layout/client/': {
      id: '/network/_layout/client/'
      path: '/client'
      fullPath: '/network/client'
      preLoaderRoute: typeof NetworkLayoutClientIndexRouteImport
      parentRoute: typeof NetworkLayoutRoute
    }
    '/_app/_layout/settings/': {
      id: '/_app/_layout/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppLayoutSettingsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/schedule/': {
      id: '/_app/_layout/schedule/'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppLayoutScheduleIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/notifications/': {
      id: '/_app/_layout/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppLayoutNotificationsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/employees/': {
      id: '/_app/_layout/employees/'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppLayoutEmployeesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/customers/': {
      id: '/_app/_layout/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppLayoutCustomersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/company/create/': {
      id: '/_app/_layout/company/create/'
      path: '/company/create'
      fullPath: '/company/create'
      preLoaderRoute: typeof AppLayoutCompanyCreateIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/business/services/': {
      id: '/_app/_layout/business/services/'
      path: '/business/services'
      fullPath: '/business/services'
      preLoaderRoute: typeof AppLayoutBusinessServicesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/business/locations/': {
      id: '/_app/_layout/business/locations/'
      path: '/business/locations'
      fullPath: '/business/locations'
      preLoaderRoute: typeof AppLayoutBusinessLocationsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/business/locations/create/': {
      id: '/_app/_layout/business/locations/create/'
      path: '/business/locations/create'
      fullPath: '/business/locations/create'
      preLoaderRoute: typeof AppLayoutBusinessLocationsCreateIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/business/locations/_location/$location_id/': {
      id: '/_app/_layout/business/locations/_location/$location_id/'
      path: '/business/locations/$location_id'
      fullPath: '/business/locations/$location_id'
      preLoaderRoute: typeof AppLayoutBusinessLocationsLocationLocation_idIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_layout/business/locations/_location/$location_id/edit/': {
      id: '/_app/_layout/business/locations/_location/$location_id/edit/'
      path: '/business/locations/$location_id/edit'
      fullPath: '/business/locations/$location_id/edit'
      preLoaderRoute: typeof AppLayoutBusinessLocationsLocationLocation_idEditIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppLayoutNotFoundRoute: typeof AppLayoutNotFoundRoute
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
  AppLayoutCustomersIndexRoute: typeof AppLayoutCustomersIndexRoute
  AppLayoutEmployeesIndexRoute: typeof AppLayoutEmployeesIndexRoute
  AppLayoutNotificationsIndexRoute: typeof AppLayoutNotificationsIndexRoute
  AppLayoutScheduleIndexRoute: typeof AppLayoutScheduleIndexRoute
  AppLayoutSettingsIndexRoute: typeof AppLayoutSettingsIndexRoute
  AppLayoutBusinessLocationsIndexRoute: typeof AppLayoutBusinessLocationsIndexRoute
  AppLayoutBusinessServicesIndexRoute: typeof AppLayoutBusinessServicesIndexRoute
  AppLayoutCompanyCreateIndexRoute: typeof AppLayoutCompanyCreateIndexRoute
  AppLayoutBusinessLocationsCreateIndexRoute: typeof AppLayoutBusinessLocationsCreateIndexRoute
  AppLayoutBusinessLocationsLocationLocation_idIndexRoute: typeof AppLayoutBusinessLocationsLocationLocation_idIndexRoute
  AppLayoutBusinessLocationsLocationLocation_idEditIndexRoute: typeof AppLayoutBusinessLocationsLocationLocation_idEditIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutNotFoundRoute: AppLayoutNotFoundRoute,
  AppLayoutIndexRoute: AppLayoutIndexRoute,
  AppLayoutCustomersIndexRoute: AppLayoutCustomersIndexRoute,
  AppLayoutEmployeesIndexRoute: AppLayoutEmployeesIndexRoute,
  AppLayoutNotificationsIndexRoute: AppLayoutNotificationsIndexRoute,
  AppLayoutScheduleIndexRoute: AppLayoutScheduleIndexRoute,
  AppLayoutSettingsIndexRoute: AppLayoutSettingsIndexRoute,
  AppLayoutBusinessLocationsIndexRoute: AppLayoutBusinessLocationsIndexRoute,
  AppLayoutBusinessServicesIndexRoute: AppLayoutBusinessServicesIndexRoute,
  AppLayoutCompanyCreateIndexRoute: AppLayoutCompanyCreateIndexRoute,
  AppLayoutBusinessLocationsCreateIndexRoute:
    AppLayoutBusinessLocationsCreateIndexRoute,
  AppLayoutBusinessLocationsLocationLocation_idIndexRoute:
    AppLayoutBusinessLocationsLocationLocation_idIndexRoute,
  AppLayoutBusinessLocationsLocationLocation_idEditIndexRoute:
    AppLayoutBusinessLocationsLocationLocation_idEditIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLayoutLoginLazyRoute: typeof AuthLayoutLoginLazyRoute
  AuthLayoutRegisterLazyRoute: typeof AuthLayoutRegisterLazyRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutLoginLazyRoute: AuthLayoutLoginLazyRoute,
  AuthLayoutRegisterLazyRoute: AuthLayoutRegisterLazyRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface NetworkLayoutRouteChildren {
  NetworkLayoutClientIndexRoute: typeof NetworkLayoutClientIndexRoute
  NetworkLayoutServerIndexRoute: typeof NetworkLayoutServerIndexRoute
}

const NetworkLayoutRouteChildren: NetworkLayoutRouteChildren = {
  NetworkLayoutClientIndexRoute: NetworkLayoutClientIndexRoute,
  NetworkLayoutServerIndexRoute: NetworkLayoutServerIndexRoute,
}

const NetworkLayoutRouteWithChildren = NetworkLayoutRoute._addFileChildren(
  NetworkLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  NetworkLayoutRoute: NetworkLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
