name: Production — CRM

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Release version to deploy"
        required: true
        type: string

env:
  REP_OWNER: ${{ vars.REP_OWNER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  IMAGE_VERSION: ${{ github.event.release.tag_name || github.event.inputs.version }}

  DEPLOY_HOST: ${{ secrets.PROD_HOST }}
  DEPLOY_USERNAME: ${{ secrets.PROD_SSH_USERNAME }}
  DEPLOY_SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
  DEPLOY_PORT: ${{ secrets.PROD_SSH_PORT }}
  DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}

jobs:
  build_and_push:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.REP_OWNER }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            VITE_API_URL=${{ vars.VITE_API_URL }}
          tags: |
            ${{ env.REP_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            ${{ env.REP_OWNER }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        env:
          IMAGE_VERSION: ${{ env.IMAGE_VERSION }}
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_SSH_PORT }}
          envs: IMAGE_VERSION
          script: |
            cd ${{ vars.DEPLOY_PATH }}

            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ vars.REP_OWNER }} --password-stdin

            docker compose -f docker-compose.prod.yml pull crm
            docker compose -f docker-compose.prod.yml stop crm
            docker compose -f docker-compose.prod.yml rm -f crm
            docker compose -f docker-compose.prod.yml up -d
            docker image prune -f
